### ISSUE TITLE
why the images are padding to 5:8 instead of 768:1024 like hd and dc?

### ISSUE THREAD

**Issue by eternaldolphin** [cuiaiyu/street-tryon-benchmark#4]

**Comment by cuiaiyu** [comment]
Two reasons:
1. We follow the unpaired virtual try-on dataset [UPT](https://arxiv.org/abs/2207.13475), which uses 5:8 as the aspect ratio.
2. The dataset is derived from [deepfashion2](https://github.com/switchablenorms/DeepFashion2) by cropping people from it. The original resolution of the deepfashion2 images is not high enough to ensure that every cropped person can be displayed clearly in 768:1024.
