### ISSUE TITLE
Data Problem

### ISSUE THREAD

**Issue by mo230761** [cuiaiyu/street-tryon-benchmark#6]
I'm very interested in your work and find it highly meaningful! However, due to personal reasons, I'm unable to download the DeepFashion2 dataset. Therefore, I would like to ask if you plan to directly provide the Street-Try-On-Benchmark dataset in the future?

**Comment by cuiaiyu** [comment]
Hi! For the license reason, you might have to obtain image access to the DeepFashion2 source to use this dataset.
