### ISSUE TITLE
How to obtain agnostic mask?

### ISSUE THREAD

**Issue by ShenZheng2000** [cuiaiyu/street-tryon-benchmark#8]
VITON methods (e.g., StableVITON) require agnostic masks, but neither DeepFashion nor Street Try-On provides them. Could you share the masks (or how to generate these masks) so I can run inference on your dataset?

**Comment by cuiaiyu** [comment]
You can check VITON-HD's code for generating the agnostic masks for reference.

https://github.com/shadow2496/VITON-HD/blob/main/datasets.py#L36

https://github.com/shadow2496/VITON-HD/blob/main/datasets.py#L36
